# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - pypy3.5

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox

# Upload reports to Codecov
after_success:
- bash < (curl -s https://codecov.io/bash)
